src/objects/Euro_Group__c.object
<CustomObject>
    <description>This stores the Euro Groups</description>
    <label>Euro Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Match__c.object
<CustomObject>
    <description>This stores all the matches</description>
    <fields>
        <fullName>Away_Goals__c</fullName>
        <label>Away Goals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Away_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Away Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches (Away Team)</relationshipLabel>
        <relationshipName>Euro_Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ground__c</fullName>
        <label>Ground</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Goals__c</fullName>
        <label>Home Goals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Kick_Off__c</fullName>
        <label>Kick-Off</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Knockout_rounds__c</fullName>
        <label>Knockout rounds</label>
        <picklist>
            <picklistValues>
                <fullName>Round of 16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter-finals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-finals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Result</label>
        <type>Checkbox</type>
    </fields>
    <label>Euro Match</label>
    <nameField>
        <label>Euro Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Team__c.object
<CustomObject>
    <description>This object stores the teams competing at the Euros</description>
    <fields>
        <fullName>Dummy_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is a place hold for the teams</inlineHelpText>
        <label>Dummy Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Teams</relationshipLabel>
        <relationshipName>Euro_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Drawn__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Drawn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Goal_Difference__c</fullName>
        <formula>Group_Goals_For__c -  Group_Goals_Against__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Goal Difference</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Goals_Against__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Goals Against</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Goals_For__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Goals For</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Lost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Lost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Played__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Played</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Points__c</fullName>
        <formula>(Group_Won__c * 3) + (Group_Drawn__c * 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Won__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Won</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Odds_Simple__c</fullName>
        <label>Odds Simple</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Odds__c</fullName>
        <label>Odds</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the person that selected the team</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Euro_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Euro Team</label>
    <nameField>
        <label>Euro Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/eurodetails.cls
public class eurodetails {

    List<Euro_Group__c> eurogroups;
    Public List<Euro_Group__c> geteurogroups() {
        if(eurogroups == null) {
            eurogroups = [select Name, (SELECT Name,Home_Team__r.Name,Away_Goals__c,Home_Goals__c,Result__c,Away_Team__r.Name,Kick_Off__c,Ground__c FROM Euro_Matches__r order by Name ASC),(SELECT Name,Group_Won__c,Group_Points__c,Group_Played__c,Group_Lost__c,Group_Goals_For__c,Group_Goals_Against__c,Group_Goal_Difference__c,Group_Drawn__c,User__c from Euro_Teams__r ORDER BY Group_Points__c DESC,Group_Goal_Difference__c DESC,Group_Goals_For__c DESC)  from Euro_Group__c order by Name ASC];
        }
        return eurogroups;
    }
    
    List<Euro_Match__c> roundof16;
    Public List<Euro_Match__c> getroundof16() {
        if(roundof16 == null) {
            roundof16 = [SELECT Name,Home_Team__r.Name,Away_Goals__c,Home_Goals__c,Result__c,Away_Team__r.Name,Kick_Off__c,Ground__c FROM Euro_Match__c where Knockout_rounds__c=:'Round of 16' order by Name ASC];
        }
        return roundof16;
    }
    
    List<Euro_Match__c> quarters;
    Public List<Euro_Match__c> getquarters() {
        if(quarters == null) {
            quarters = [SELECT Name,Home_Team__r.Name,Away_Goals__c,Home_Goals__c,Result__c,Away_Team__r.Name,Kick_Off__c,Ground__c FROM Euro_Match__c where Knockout_rounds__c=:'Quarter-finals' order by Name ASC];
        }
        return quarters;
    }
    
    List<Euro_Match__c> semis;
    Public List<Euro_Match__c> getsemis() {
        if(semis == null) {
            semis = [SELECT Name,Home_Team__r.Name,Away_Goals__c,Home_Goals__c,Result__c,Away_Team__r.Name,Kick_Off__c,Ground__c FROM Euro_Match__c where Knockout_rounds__c=:'Semi-finals' order by Name ASC];
        }
        return semis;
    }
    
    List<Euro_Match__c> grandfinal;
    Public List<Euro_Match__c> getgrandfinal() {
        if(grandfinal == null) {
            grandfinal = [SELECT Name,Home_Team__r.Name,Away_Goals__c,Home_Goals__c,Result__c,Away_Team__r.Name,Kick_Off__c,Ground__c FROM Euro_Match__c where Knockout_rounds__c=:'Final' order by Name ASC];
        }
        return grandfinal;
    }
    
    List<Euro_Team__c> myteam;
    Public List<Euro_Team__c> getmyteam() {
        if(myteam== null){
            myteam = [SELECT Name,Odds__c,User__c,User__r.Name from Euro_Team__c WHERE Dummy_Team__c=:false and User__c=:UserInfo.getUserId() ORDER BY Odds_Simple__c ASC, Name ASC];
        }
        return myteam;
    }
}