src/objects/Euro_Group__c.object
<CustomObject>
    <description>This stores the Euro Groups</description>
    <label>Euro Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Match__c.object
<CustomObject>
    <description>This stores all the matches</description>
    <fields>
        <fullName>Away_Goals__c</fullName>
        <label>Away Goals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Away_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Away Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches (Away Team)</relationshipLabel>
        <relationshipName>Euro_Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Home_Goals__c</fullName>
        <label>Home Goals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Result</label>
        <type>Checkbox</type>
    </fields>
    <label>Euro Match</label>
    <nameField>
        <label>Euro Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Team__c.object
<CustomObject>
    <description>This object stores the teams competing at the Euros</description>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Teams</relationshipLabel>
        <relationshipName>Euro_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Drawn__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Drawn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Goals_Against__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Goals Against</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Goals_For__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Goals For</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Lost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Lost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Played__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Played</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Group_Won__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Won</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Euro Team</label>
    <nameField>
        <label>Euro Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EuroTriggers.cls
public class EuroTriggers {

    public static void matchmanagement(List<Euro_Match__c> lstmatches){
        for(Euro_Match__c match:lstmatches){
            // PERFORM GROUP STAGE MANAGEMENT
            if(match.Result__c==true && match.Euro_Group__c!=null){
                // get a list of home teams
               List<Euro_Team__c> hometeam = [select id,Group_Goals_For__c,Group_Goals_Against__c,Group_Played__c,Group_Drawn__c,Group_Won__c,Group_Lost__c from Euro_Team__c where ID=:match.Home_Team__c];
                // get a list of away teams
              List<Euro_Team__c> awayteam = [select id,Group_Goals_For__c,Group_Goals_Against__c,Group_Played__c,Group_Drawn__c,Group_Won__c,Group_Lost__c from Euro_Team__c where ID=:match.Away_Team__c];
                
                // loop through home teams              
              for(Euro_Team__c ht:hometeam){
                ht.Group_Goals_For__c = ht.Group_Goals_For__c+match.Home_Goals__c;
                ht.Group_Goals_Against__c = ht.Group_Goals_Against__c+match.Away_Goals__c;
                ht.Group_Played__c = ht.Group_Played__c+1;
                if(match.Home_Goals__c==match.Away_Goals__c){
                    ht.Group_Drawn__c = ht.Group_Drawn__c+1;
                }
                if(match.Home_Goals__c>match.Away_Goals__c){
                    ht.Group_Won__c = ht.Group_Won__c+1;
                }
                if(match.Home_Goals__c<match.Away_Goals__c){
                    ht.Group_Lost__c = ht.Group_Lost__c+1;
                }
                update ht;
              }
                // loop through away teams
              for(Euro_Team__c at:awayteam){
                at.Group_Goals_For__c = at.Group_Goals_For__c+match.Away_Goals__c;
                at.Group_Goals_Against__c = at.Group_Goals_Against__c+match.Home_Goals__c;
                at.Group_Played__c = at.Group_Played__c+1;
                if(match.Home_Goals__c==match.Away_Goals__c){
                    at.Group_Drawn__c = at.Group_Drawn__c+1;
                }
                if(match.Home_Goals__c<match.Away_Goals__c){
                    at.Group_Won__c = at.Group_Won__c+1;
                }
                if(match.Home_Goals__c>match.Away_Goals__c){
                    at.Group_Lost__c = at.Group_Lost__c+1;
                }
                update at;
              }
            }
        }
    }
}