src/objects/Euro_Group__c.object
<CustomObject>
    <description>This stores the Euro Groups</description>
    <label>Euro Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Match__c.object
<CustomObject>
    <description>This stores all the matches</description>
    <fields>
        <fullName>Away_Goals__c</fullName>
        <label>Away Goals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Away_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Away Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches (Away Team)</relationshipLabel>
        <relationshipName>Euro_Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Home_Goals__c</fullName>
        <label>Home Goals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result_Shared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Result Shared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Result</label>
        <type>Checkbox</type>
    </fields>
    <label>Euro Match</label>
    <nameField>
        <label>Euro Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Team__c.object
<CustomObject>
    <description>This object stores the teams competing at the Euros</description>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Teams</relationshipLabel>
        <relationshipName>Euro_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Points__c</fullName>
        <formula>(Group_Won__c * 3) + (Group_Drawn__c * 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Euro Team</label>
    <nameField>
        <label>Euro Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EuroTriggersTest.cls
@isTest 
private class EuroTriggersTest {
    private static Euro_Group__c eg;
    private static Euro_Team__c et1;
    private static Euro_Team__c et2;
    private static Euro_Match__c mt;
    
    private static void setupData(){
        eg = new Euro_Group__c(Name='Group A');
        insert eg;
        
        et1 = new Euro_Team__c(Name='France',Euro_Group__c=eg.id);
        insert et1;
        
        et2 = new Euro_Team__c(Name='England',Euro_Group__c=eg.id);
        insert et2;
        
        mt = new Euro_Match__c(Name='10 Jun',Home_Team__c=et1.id,Away_Team__c=et2.id,Euro_Group__c=eg.id,Result_Shared__c=true);
        insert mt;

    }
    
    static testMethod void test_homewin(){
        setupData();
        
        mt.Home_Goals__c=2;
        mt.Away_Goals__c=1;
        mt.Result__c=true;
        update mt;
        
        integer homepoints = [select count() from Euro_Team__c where Name=:'France' and Group_Points__c=:3];
        system.assertequals(1,homepoints);
        integer awaypoints = [select count() from Euro_Team__c where Name=:'England' and Group_Points__c=:0];
        system.assertequals(1,awaypoints);
    }
    
    static testMethod void test_awaywin(){
        setupData();
        
        mt.Home_Goals__c=2;
        mt.Away_Goals__c=3;
        mt.Result__c=true;
        update mt;
        
        integer homepoints = [select count() from Euro_Team__c where Name=:'France' and Group_Points__c=:0];
        system.assertequals(1,homepoints);
        integer awaypoints = [select count() from Euro_Team__c where Name=:'England' and Group_Points__c=:3];
        system.assertequals(1,awaypoints);
    
    }
    
    static testMethod void test_draw(){
        setupData();
        
        mt.Home_Goals__c=2;
        mt.Away_Goals__c=2;
        mt.Result__c=true;
        update mt;
        
        integer homepoints = [select count() from Euro_Team__c where Name=:'France' and Group_Points__c=:1];
        system.assertequals(1,homepoints);
        integer awaypoints = [select count() from Euro_Team__c where Name=:'England' and Group_Points__c=:1];
        system.assertequals(1,awaypoints);
    
    }
}