src/objects/Euro_Group__c.object
<CustomObject>
    <description>This stores the Euro Groups</description>
    <label>Euro Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Match__c.object
<CustomObject>
    <description>This stores all the matches</description>
    <fields>
        <fullName>Away_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Away Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches (Away Team)</relationshipLabel>
        <relationshipName>Euro_Matches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Euro_Team__c</referenceTo>
        <relationshipLabel>Euro Matches</relationshipLabel>
        <relationshipName>Euro_Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result_Shared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Result Shared</label>
        <type>Checkbox</type>
    </fields>
    <label>Euro Match</label>
    <nameField>
        <label>Euro Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Euro_Team__c.object
<CustomObject>
    <description>This object stores the teams competing at the Euros</description>
    <fields>
        <fullName>Euro_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Euro Group</label>
        <referenceTo>Euro_Group__c</referenceTo>
        <relationshipLabel>Euro Teams</relationshipLabel>
        <relationshipName>Euro_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RegistrationChatterPostSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RegistrationChatterPostSent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the person that selected the team</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Euro_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Euro Team</label>
    <nameField>
        <label>Euro Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Euro Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/euromyteamTest.cls
@isTest 
private class euromyteamTest {    
    static testMethod void test_all_basic(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u1 = new User(Alias = 'standt1',Country='United Kingdom',Email='demo1@randomdemodomain.com',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles', UserName='dprobertdemo1@camfed.org');
        insert u1;
        
        Euro_Group__c eg = new Euro_Group__c(Name='Group A');
        insert eg;
        
        Euro_Team__c et1 = new Euro_Team__c(Name='France',Euro_Group__c=eg.id,User__c=u1.id,RegistrationChatterPostSent__c=true);
        insert et1;
        
        Euro_Team__c et2 = new Euro_Team__c(Name='England',Euro_Group__c=eg.id);
        insert et2;
        
        Euro_Match__c mt = new Euro_Match__c(Name='10 Jun',Home_Team__c=et1.id,Away_Team__c=et2.id,Euro_Group__c=eg.id,Result_Shared__c=true);
        insert mt;

        System.runAs(u1){
            PageReference pageRef = Page.EuroMyTeam;
            Test.setCurrentPage(pageRef);
            euromyteam controller = new euromyteam();
    
            controller.getfixtures();
            controller.getmyteam();
        }
    }
}